<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>GBFR.ChatOverlay.ConfiguratorUI</AssemblyName>
    <RootNamespace>GBFR.ChatOverlay.ConfiguratorUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.3.0" ExcludeAssets="runtime" />
  </ItemGroup>

</Project>
